#!/usr/bin/env python3
"""Embed a PNG as an LVGL image (decoded by LodePNG at first use).
Usage: png_to_c.py <in.png> <symbol> <out.c>"""
import struct
import sys

src, name, out = sys.argv[1:4]
data = open(src, "rb").read()
w, h = struct.unpack(">II", data[16:24])
lines = ["    " + ",".join("0x%02x" % b for b in data[i:i + 20]) + "," for i in range(0, len(data), 20)]
with open(out, "w") as f:
    f.write("/* Generated by tools/png_to_c.py - do not edit */\n#include \"lvgl.h\"\n\n")
    f.write("static const uint8_t %s_png[] = {\n%s\n};\n\n" % (name, "\n".join(lines)))
    f.write("const lv_image_dsc_t %s = {\n    .header.magic = LV_IMAGE_HEADER_MAGIC,\n" % name)
    f.write("    .header.cf = LV_COLOR_FORMAT_RAW_ALPHA,\n    .header.w = %d,\n    .header.h = %d,\n" % (w, h))
    f.write("    .data_size = sizeof(%s_png),\n    .data = %s_png,\n};\n" % (name, name))
