#!/usr/bin/env python3
"""Embed the dash stencil PNG into a C file for the simulator.

Usage: stencil_to_c.py <out.c>

Uses assets/stencil.png if it exists, otherwise assets/stencil_placeholder.png.
The image is normalised to 1920x720 RGBA:
  - PNG with transparency: used as-is (transparent = visible screen area).
  - PNG/JPG without transparency: near-white pixels become transparent
    (white = visible screen area, dark = bezel).
"""
import io
import os
import sys

from PIL import Image

W, H = 1920, 720
ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
ASSETS = os.path.join(ROOT, "assets")


def pick_source():
    for name in ("stencil.png", "stencil.jpg", "stencil_placeholder.png"):
        path = os.path.join(ASSETS, name)
        if os.path.exists(path):
            return path
    sys.exit("no stencil image found in assets/")


def load(path):
    img = Image.open(path)
    has_alpha = img.mode in ("RGBA", "LA") or "transparency" in img.info
    img = img.convert("RGBA")
    if img.size != (W, H):
        img = img.resize((W, H), Image.LANCZOS)
    if not has_alpha:
        px = img.load()
        for y in range(H):
            for x in range(W):
                r, g, b, _ = px[x, y]
                if r > 230 and g > 230 and b > 230:
                    px[x, y] = (0, 0, 0, 0)
    return img


def main():
    out_path = sys.argv[1]
    src = pick_source()
    buf = io.BytesIO()
    load(src).save(buf, format="PNG", optimize=True)
    data = buf.getvalue()

    lines = []
    for i in range(0, len(data), 20):
        lines.append("    " + ",".join("0x%02x" % b for b in data[i:i + 20]) + ",")

    with open(out_path, "w") as f:
        f.write("/* Generated by tools/stencil_to_c.py from %s - do not edit */\n"
                % os.path.basename(src))
        f.write('#include "lvgl.h"\n\n')
        f.write("static const uint8_t stencil_png[] = {\n%s\n};\n\n" % "\n".join(lines))
        f.write("const lv_image_dsc_t stencil_img = {\n")
        f.write("    .header.magic = LV_IMAGE_HEADER_MAGIC,\n")
        f.write("    .header.cf = LV_COLOR_FORMAT_RAW_ALPHA,\n")
        f.write("    .header.w = %d,\n    .header.h = %d,\n" % (W, H))
        f.write("    .data_size = sizeof(stencil_png),\n")
        f.write("    .data = stencil_png,\n};\n")
    print("stencil: %s -> %s (%d bytes)" % (src, out_path, len(data)))


if __name__ == "__main__":
    main()
